"use strict";
const $ = (s) => document.querySelector(s);
const state = { files: [], current: null, original: "", job: null, poll: null };
const toast = (message) => { const el=$("#toast"); el.textContent=message; el.classList.add("show"); setTimeout(()=>el.classList.remove("show"),2200); };
async function api(path, options={}) { const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options}); const body=await r.json().catch(()=>({error:`HTTP ${r.status}`})); if(!r.ok) throw new Error(body.error||`HTTP ${r.status}`); return body; }
function isDirty(){ return state.current !== null && $("#editor").value !== state.original; }
function renderDirty(){ const dirty=isDirty(); $("#dirty").classList.toggle("hidden",!dirty); $("#save").disabled=!dirty; }
async function loadFiles(){ const data=await api("/api/files"); state.files=data.files; $("#workspace").textContent=` · ${data.workspace}`; renderFiles(); }
function renderFiles(){ const q=$("#filter").value.toLowerCase(); const nav=$("#files"); nav.replaceChildren(); for(const path of state.files.filter(x=>x.toLowerCase().includes(q))){ const b=document.createElement("button"); b.type="button"; b.className="file"+(path===state.current?" active":""); b.textContent=path; b.title=path; b.onclick=()=>openFile(path); nav.appendChild(b); } }
async function guardDiscard(){ if(!isDirty()) return true; return window.confirm("Discard unsaved changes?"); }
async function openFile(path){ if(path===state.current || !(await guardDiscard())) return; const data=await api(`/api/file?path=${encodeURIComponent(path)}`); state.current=path; state.original=data.content; $("#editor").value=data.content; $("#current-file").textContent=path; $("#empty").classList.add("hidden"); $("#editor-wrap").classList.remove("hidden"); renderFiles(); renderDirty(); }
async function save(){ if(!state.current) return; const data=await api("/api/file",{method:"PUT",body:JSON.stringify({path:state.current,content:$("#editor").value})}); state.original=$("#editor").value; renderDirty(); toast(data.backup?`Saved. Backup: ${data.backup}`:"Saved."); }
async function run(){ if(isDirty()){ toast("Save or discard changes before running."); return; } const competence=$("#competence").value; if(!competence){ toast("Choose a competence month."); return; } const data=await api("/api/pipeline",{method:"POST",body:JSON.stringify({competence,agency:$("#agency").value,force:$("#force").checked,clean:$("#clean").checked})}); state.job=data.job_id; $("#run").disabled=true; $("#stop").classList.remove("hidden"); $("#output").textContent=`Started: ${data.command}\n`; poll(); state.poll=setInterval(poll,900); }
async function poll(){ if(!state.job) return; try{ const data=await api(`/api/pipeline/${state.job}`); $("#output").textContent=data.output||"Running..."; $("#output").scrollTop=$("#output").scrollHeight; if(data.status!=="running"){ clearInterval(state.poll); state.poll=null; state.job=null; $("#run").disabled=false; $("#stop").classList.add("hidden"); toast(`Pipeline ${data.status}.`); } }catch(e){ clearInterval(state.poll); $("#run").disabled=false; toast(e.message); } }
async function stop(){ if(!state.job) return; await api(`/api/pipeline/${state.job}`,{method:"DELETE"}); }
$("#editor").addEventListener("input",renderDirty); $("#filter").addEventListener("input",renderFiles); $("#save").addEventListener("click",()=>save().catch(e=>toast(e.message))); $("#reload").addEventListener("click",async()=>{if(await guardDiscard()){state.current=null; await loadFiles(); toast("File list reloaded.");}}); $("#run").addEventListener("click",()=>run().catch(e=>toast(e.message))); $("#stop").addEventListener("click",()=>stop().catch(e=>toast(e.message))); window.addEventListener("beforeunload",e=>{if(isDirty()){e.preventDefault();e.returnValue="";}});
const d=new Date(); d.setMonth(d.getMonth()-1); $("#competence").value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`; loadFiles().catch(e=>toast(e.message));
