"""Adapter plano→execução: converte cada passo do pipeline numa chamada ao
comando `cli.*` correspondente (ticket 06 SRP).

Extraído de `orchestration/run.py`: concentra o acoplamento com `cli.*`,
`config.resolution`, `excel.*` e `capa_paths` — resolve pré-condições
(`dependency_missing`), verifica artefatos próprios (`_own_artifact_missing`)
e despacha a execução (`_dispatch`). A topologia vive em `plan.py`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Final

from pyauditor.capa_paths import resolve_capa_path
from pyauditor.cli.bootstrap import run_bootstrap
from pyauditor.cli.consolidate import check_consolidate_ready, run_consolidate
from pyauditor.cli.dependencies import CHECKERS
from pyauditor.cli.measure import run_measure
from pyauditor.cli.report import check_report_ready, run_report
from pyauditor.cli.split import (
    _SINTETICO_FILENAME,
    run_split,
)
from pyauditor.config.resolution import per_orgao_paths
from pyauditor.excel.equipe import EQUIPE_FILENAME
from pyauditor.excel.objetos import OBJETOS_FILENAME
from pyauditor.excel.prazos import PRAZOS_FILENAME
from pyauditor.orchestration.plan import ORGANIZATION_COMMANDS

if TYPE_CHECKING:
    from pyauditor.periodo import PeriodoAfericao

    from .run import CommandResult, RunRequest

__all__: Final[tuple[str, ...]] = (
    "OrgaoContractError",
    "dependency_missing",
    "dispatch",
)


class OrgaoContractError(ValueError):
    """Contrato de organização inválido para um comando."""


def _require_orgao(
    command: str,
    orgao: str | None,
) -> str:
    """Return the organization required by an organization-specific command."""
    if command not in ORGANIZATION_COMMANDS:
        raise OrgaoContractError(f"Command {command!r} is not organization-specific")

    if orgao not in {"MinC", "MTur"}:
        raise OrgaoContractError(
            f"Command {command!r} requires orgao 'MinC' or 'MTur', received {orgao!r}"
        )

    return orgao


def dependency_missing(
    command: str,
    orgao: str | None,
    request: RunRequest,
) -> tuple[str, ...]:
    """Return missing upstream dependencies for one planned command.

    Report and consolidation checks are dispatched explicitly so their typed
    parameter contracts remain visible to static analysis. Zero-argument
    checkers use the runtime registry.

    Raises:
        ValueError: If the command is unknown or its organization contract is
            invalid.
    """
    if command == "report":
        organization = _require_orgao(command, orgao)
        check = check_report_ready(
            request.competencia,
            organization,
            request.capa_path,
            request.output_dir / organization,
            data_dir=request.data_dir,
        )
        return check.missing

    if command == "consolidate":
        if orgao is not None:
            raise ValueError("consolidate must not receive an organization")

        check = check_consolidate_ready(
            request.competencia,
            request.report_dir,
            request.output_dir,
        )
        return check.missing

    if command not in ORGANIZATION_COMMANDS:
        raise ValueError(f"Unsupported command: {command!r}")

    _require_orgao(command, orgao)

    checker = CHECKERS.get(command)
    if checker is None:
        raise ValueError(f"No dependency checker registered for command {command!r}")

    return checker().missing


def own_artifact_missing(
    command: str,
    orgao: str | None,
    request: RunRequest,
) -> str | None:
    """Return an actionable message when a completed artifact disappeared.

    This check applies to commands whose dependency checkers do not validate
    their own outputs. Report and consolidation are normally regenerated by
    ``force_commands`` and are therefore excluded.
    """
    if command == "bootstrap":
        organization = _require_orgao(command, orgao)
        capa_path = resolve_capa_path(
            request.capa_path,
            organization,
        )

        if not capa_path.is_file():
            return f"capa de {organization} ausente em {capa_path}; execute bootstrap novamente"

        return None

    if command == "split":
        organization = _require_orgao(command, orgao)
        sintetico_path = (
            request.report_dir / organization / request.competencia / _SINTETICO_FILENAME
        )

        if not sintetico_path.is_file():
            return f"artefato de split ausente em {sintetico_path}; execute split novamente"

        return None

    if command == "measure":
        organization = _require_orgao(command, orgao)
        roms_dir = request.output_dir / organization / request.competencia

        if not roms_dir.is_dir():
            return f"diretório de ROMs ausente em {roms_dir}; execute measure novamente"

        return None

    if command in {"report", "consolidate"}:
        return None

    raise ValueError(f"Unsupported command: {command!r}")


def dispatch(
    command: str,
    orgao: str | None,
    request: RunRequest,
    periodo: PeriodoAfericao,
    *,
    already_split: bool = False,
) -> CommandResult:
    """Execute one planned command using validated arguments.

    ``already_split`` (ticket 05/11): only honored by `measure` — whether
    `split` actually ran in this invocation, so the in-memory categorical
    path can suppress the duplicate `in_values`/`outros` warnings it would
    otherwise re-emit for the same raw dataset.
    """
    if command == "bootstrap":
        organization = _require_orgao(command, orgao)
        capa_path = resolve_capa_path(
            request.capa_path,
            organization,
        )
        return run_bootstrap(capa_path, organization)

    if command == "split":
        organization = _require_orgao(command, orgao)
        paths = per_orgao_paths(
            config_dir=request.config_dir,
            data_dir=request.data_dir,
            output_dir=request.output_dir,
            report_dir=request.report_dir,
            orgao=organization,
        )

        return run_split(
            request.competencia,
            paths.config_dir,
            paths.data_dir,
            expected_orgao=organization,
            manifest=paths.manifest,
            report_dir=paths.report_dir,
            materialize=False,
            periodo=periodo,
            strict=request.strict,
            prazos_path=request.data_dir / PRAZOS_FILENAME,
            capa_path=request.capa_path,
            equipe_path=request.data_dir / EQUIPE_FILENAME,
            objetos_path=request.data_dir / OBJETOS_FILENAME,
        )

    if command == "measure":
        organization = _require_orgao(command, orgao)
        paths = per_orgao_paths(
            config_dir=request.config_dir,
            data_dir=request.data_dir,
            output_dir=request.output_dir,
            orgao=organization,
        )

        return run_measure(
            competencia=request.competencia,
            config_dir=paths.config_dir,
            data_dir=paths.data_dir,
            output_dir=paths.output_dir,
            manifest=paths.manifest,
            expected_orgao=organization,
            equipe_path=request.data_dir / EQUIPE_FILENAME,
            periodo=periodo,
            strict=request.strict,
            already_split=already_split,
        )

    if command == "report":
        organization = _require_orgao(command, orgao)
        paths = per_orgao_paths(
            config_dir=request.config_dir,
            data_dir=request.data_dir,
            output_dir=request.output_dir,
            orgao=organization,
        )
        output_path = request.report_dir / f"relatorio_{request.competencia}_{organization}.xlsx"

        return run_report(
            competencia=request.competencia,
            capa_path=request.capa_path,
            roms_dir=paths.output_dir,
            output_path=output_path,
            config_dir=paths.config_dir,
            expected_orgao=organization,
            is_final_month=request.final_month,
            data_dir=request.data_dir,
        )

    if command == "consolidate":
        if orgao is not None:
            raise ValueError("consolidate must not receive an organization")

        output_path = request.report_dir / f"relatorio_{request.competencia}_consolidado.xlsx"

        return run_consolidate(
            competencia=request.competencia,
            report_dir=request.report_dir,
            roms_dir=request.output_dir,
            output_path=output_path,
            data_dir=request.data_dir,
            is_final_month=request.final_month,
        )

    raise ValueError(f"Unsupported command: {command!r}")